const ranks = [
  'Factorial Flatbread',
  'Exponential Eclair',
  'Polynomial Pita',
  'Cubic Croissant',
  'Quadratic Qornbread',
  'Linear Loaf',
  'nlog Naan',
  'Constant Cornbread',
  'Binary Baguette',
  'Boolean Biscuit',
  'Byte-sized Bagel',
  'Gigabit Gingerbread',
  'Hashed Hashbrown',
  'Recursed Ravioli',
  'Algorithmic Apple Pie',
  'Kernel Krispie',
  'Virtual Viennoiserie',
  'Cybernetic Scone',
  'Quantum Quiche',
  'Firewall Flan',
  'Turing Tart',
  'Syntax Soufflé',
  'Debugging Danish',
  'Neural Network Nougat',
  'Blessed Boba',
  'Super Snu',
  'Soon(TM)',
  'Later(TM)',
  'Sometime(TM)',
  'We Ran Out Of Ranks',
];

export default ranks;
